config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'
  resources :gossip do 
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :users
  resources :sessions
  resources :city
  get 'authorized', to: 'sessions#page_requires_login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200 }
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :content
	has_many :comment_of_comments
end

app/models/comments.rb
class Comments < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200 }
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :content
	has_many :comment_of_comments
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 14}
  validates :content, presence: true, length: {minimum: 3, maximum: 300}
  belongs_to :user
  has_many :comments
  has_many :join_table_gossips_tags
  has_many :tags, through: :join_table_gossips_tags
end

app/models/jake.rb
class Jake < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossips_tags
	has_many :gossips, through: :join_table_gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true, format: { with: /\w+@\w+\.{1}[a-zA-Z]{2,}/, message: "Veuillez renseigner une adresse mail valide." }
	validates :password, presence: true, length: { minimum: 6 }
	
	belongs_to :city, optional: true
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :comments
	has_many :likes
	has_many :comment_of_comments
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
def show
  @city = City.find(params[:id])
end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def all
    puts "On affiche les potins."
  end

  def show
    puts "On affiche les potins separement."
    @gossip = Gossip.find(params[:id])
    @author = Gossip.find(params[:id]).user.first_name + "#{Gossip.find(params[:id]).user.last_name}"
    @title = Gossip.find(params[:id]).title
    @creation_date = Gossip.find(params[:id]).created_at
  end

  def new
  end

  def create
      puts "La méthode create s'est lancée correctement."
      @gossip = Gossip.new(title: params[:title], content: params[:body], user_id: 12)
      if @gossip.save
        flash[:notice] = "Votre gossip a bien été sauvegardé."
        redirect_to root_path
      else
        @errors = @gossip.errors
        render new_gossip_path
      end
  end

  def update
    puts "La méthode update s'est lancée correctement."
    @gossip = Gossip.find(params[:id])
  if @gossip.update(title: params[:title], content: params[:body])
    redirect_to @gossip
  else
    render :edit
  end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.delete
    redirect_to root_path
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/all.html.erb
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>The Gossip Project.</title>
</head>
<body>
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Bienvenue sur The <small class="text-muted">Gossip</small> Project.</h1>
      <p class="lead">Le premier site de ragoting de France.</p>
    </div>
  </div>  
  <div class="body_welcome">
<% Gossip.all.each do |gossip| %>  
<div class="cards-div">
  <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><strong>Titre:</strong> <%= gossip.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Auteur: <%=link_to gossip.user.first_name, user_path(gossip.user.id) %></h6>
    <p class="card-text"><%=h truncate(gossip.content, :length => 30) %></p>
    <a class="card-link"><%= link_to 'En voir plus', gossip_path(gossip.id) %></a>
  </div>
</div>
</div>
  <% end %></div>
  
  </body>
</html>

app/views/gossip/edit.html.erb
<h1>Bienvenue sur la page d'édition de gossip.</h1>
<%= form_tag url_for(action: 'update'), method: "patch" do %>
  <%= label_tag 'Titre' %>
  <%= text_field_tag 'title' %>
  <br /> <br />

  <%= label_tag 'Contenu' %>
  <%= text_area_tag 'body' %>
  <br /> <br />

  <%= submit_tag "Edit Post" %>

  <% end %>

app/views/gossip/new.html.erb
<div class="text-center mt-5">
<h1>Ici, tu peux créer un nouveau gossip.</h1>
<% if @errors%>
  <% @errors.messages.each do |message|%>
  <div class="alert alert-danger" role="alert">
  Le champ <%= message[0] %> a le problème suivant: <%= message[1][0] %>
  </div>
    <% end%>
  <% end %>
<%= form_tag url_for(action: 'create'), method: "post" do %>
  <%= label_tag 'Titre' %>
  <%= text_field_tag 'title' %>
  <br /> <br />

  <%= label_tag 'Contenu' %>
  <%= text_area_tag 'body' %>
  <br /> <br />

  <%= submit_tag "Create Post" %>

  <% end %>
  </div>

app/views/gossip/show.html.erb
<div class="body_welcome">
  <p>Posté par: <%= link_to @author, user_path(@gossip.user.id) %></p>
  <h3>Titre: <%= @title %></h3>
  <p>Le gossip :</p>
  <p><%= @gossip.content %></p>
  <p>Créé le: <%= @creation_date %></p>
  <p>A: <%= link_to @gossip.user.city.name, city_path(@gossip.user.city_id) %></p>
  <p><%= link_to "Editer le gossip", edit_gossip_path %></p>
  <p><%= link_to "Effacer le gossip", gossip_path(@gossip.id), method: :delete, data: { confirm: 'Êtes-vous sûr.e ?' }%></p>
  <%= render 'comments/form'%>
  <% Comment.all.each do |comment| %>
    <% if comment.gossip.id == @gossip.id%>
      <p><%= comment.content %></p>
      <%end%>
  <%end%>
</div>