config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'
  resources :gossip do 
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :users
  resources :sessions
  resources :city
  get 'authorized', to: 'sessions#page_requires_login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200 }
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :content
	has_many :comment_of_comments
end

app/models/comments.rb
class Comments < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200 }
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :content
	has_many :comment_of_comments
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 14}
  validates :content, presence: true, length: {minimum: 3, maximum: 300}
  belongs_to :user
  has_many :comments
  has_many :join_table_gossips_tags
  has_many :tags, through: :join_table_gossips_tags
end

app/models/jake.rb
class Jake < ApplicationRecord
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossips_tags
	has_many :gossips, through: :join_table_gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true, format: { with: /\w+@\w+\.{1}[a-zA-Z]{2,}/, message: "Veuillez renseigner une adresse mail valide." }
	validates :password, presence: true, length: { minimum: 6 }
	
	belongs_to :city, optional: true
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :comments
	has_many :likes
	has_many :comment_of_comments
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
def show
  @city = City.find(params[:id])
end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authorized, only: [:new, :create]

  def new
  end

  def create
    puts "$" * 60
    puts "ceci est le contenu de params :"
    puts params
    puts "$" * 60
    User.create(first_name: params[:user_name], password: params[:password])
    redirect_to '/welcome'
  end

  def show
    @author = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/new.html.erb
<h1>Creer un nouveau compte</h1>
<div class="form-group">
    <form action= <%= users_path %> method="POST">
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
      <label>Comment vous appelez-vous ?</label>
      <input type="text" class="form-control" name="user_name"/>
      <label>Quel mot de passe desirez-vous utiliser ?</label>
      <input type="text" class="form-control" name="password">
      <br/>
      <input type='submit' class="btn btn-primary" value="Creer un compte" style="margin-top: 10px;"/>
    </form>
  </div>

app/views/users/show.html.erb
<h1>Bienvenue sur la page de <%= @author.first_name %> <%= @author.last_name %></h1>
<p>Nom : <%= @author.last_name %></p>
<p>Prénom : <%= @author.first_name %></p>
<p>Description : <%= @author.description %></p>
<p>e-mail : <%= @author.email %></p>
<p>Âge : <%= @author.age %></p>
<p>Ville : <%= link_to @author.city.name, city_path(@author.city_id) %></p>