config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show'
  resources :gossip do 
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :users
  resources :sessions
  resources :city
  get 'authorized', to: 'sessions#page_requires_login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200 }
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :content
	has_many :comment_of_comments
end

app/models/comments.rb
class Comments < ApplicationRecord
  validates :content, presence: true, length: { maximum: 200 }
  belongs_to :gossip
  belongs_to :user
  has_many :likes, as: :content
	has_many :comment_of_comments
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 14}
  validates :content, presence: true, length: {minimum: 3, maximum: 300}
  belongs_to :user
  has_many :comments
  has_many :join_table_gossips_tags
  has_many :tags, through: :join_table_gossips_tags
end

app/models/jake.rb
class Jake < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossips_tags
	has_many :gossips, through: :join_table_gossips_tags
end

app/models/user.rb
class User < ApplicationRecord
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, presence: true, uniqueness: true, format: { with: /\w+@\w+\.{1}[a-zA-Z]{2,}/, message: "Veuillez renseigner une adresse mail valide." }
	validates :password, presence: true, length: { minimum: 6 }
	
	belongs_to :city, optional: true
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :comments
	has_many :likes
	has_many :comment_of_comments
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
def show
  @city = City.find(params[:id])
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>TheGossipProject.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Tgp.</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link" %><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to "Publier un gossip", new_gossip_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "L'équipe", team_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact", contact_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Se connecter
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "J'ai déjà un compte", new_session_path, class: "nav-link" %>
              <%= link_to "Créer un compte", root_path, class: "nav-link" %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </head>

  <body>
    <%= yield %>
  </body>
</html>